version: '3.7'

services:
  iotfreezer-backend:
    container_name: iotfreezer-backend
    build:
      context: ./backend
    ports:
      - 8010:3001
    command: yarn run start
    depends_on:
      - postgres
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
    networks:
      - webnet
    env_file:
      - ./backend/.env
  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_USER: ${POSTGRES_USER}
      # POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
    networks:
      - webnet
    env_file:
      - ./backend/.env
  iotfreezer-frontend:
    container_name: iotfreezer-frontend
    env_file:
      - ./frontend/.env
    build:
      context: ./frontend
    ports:
      - 8011:80
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    networks:
      - webnet
  nginx:
    image: nginx:1.15-alpine
    ports:
      # - "80:80"
      - "8012:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
networks:
  webnet:
volumes:
  pgdata: