version: '3.7'

services:
  iotfreezer-backend:
    container_name: iotfreezer-backend
    build:
      context: ./backend
    ports:
      - ${DOCKER_MAPPED_PORT}:${SERVER_PORT}
    command: yarn run start
    env_file:
      - .env
    depends_on:
      - postgres
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
    networks:
      - webnet
    env_file:
    - ./backend/.env
  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
    networks:
      - webnet
    env_file:
      - ./backend/.env
  iotfreezer-frontend:
    container_name: iotfreezer-frontend
    env_file:
      - ./frontend/.env
    build:
      context: ./frontend
    ports:
      - ${SERVER_PORT}:80
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    networks:
      - webnet
networks:
  webnet:
volumes:
  pgdata: