version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    ports:
      - 3000:${SERVER_PORT}
    command: yarn run start
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgrestest
      - postgres
  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  postgrestest:
    container_name: postgrestest
    image: postgres:12
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - 5434:5432
networks:
  webnet:
volumes:
  pgdata: