version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    ports:
      - ${DOCKER_MAPPED_PORT}:${SERVER_PORT}
    command: yarn run start
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgrestest
      - postgres
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
  postgrestest:
    container_name: postgrestest
    image: postgres:12
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - 5433:5432
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
networks:
  webnet:
volumes:
  pgdata: